# Generated by Django 2.2 on 2020-05-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=25)),
                ('profile', models.TextField()),
                ('sites', models.TextField()),
                ('members', models.TextField()),
                ('albums', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=45)),
            ],
        ),
    ]
