# Generated by Django 2.2 on 2020-05-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0006_artistinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtistInfo',
        ),
    ]
