# Generated by Django 2.2 on 2020-05-17 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0007_delete_artistinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=25)),
                ('profile', models.TextField()),
                ('sites', models.TextField()),
                ('members', models.TextField()),
                ('albums', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artistinfo', to='logreg.User')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.TextField()),
                ('label', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=75)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albuminfo', to='logreg.User')),
            ],
        ),
    ]
