# Generated by Django 2.2 on 2020-05-17 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0010_albuminfo_artistinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistinfo',
            name='albums',
        ),
        migrations.RemoveField(
            model_name='artistinfo',
            name='label',
        ),
        migrations.RemoveField(
            model_name='artistinfo',
            name='sites',
        ),
        migrations.RemoveField(
            model_name='artistinfo',
            name='state',
        ),
    ]
