# Generated by Django 2.2 on 2020-05-17 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0011_auto_20200517_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='logreg.User'),
        ),
    ]
