# Generated by Django 2.2 on 2020-05-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0014_auto_20200518_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistinfo',
            name='members',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='artistinfo',
            name='profile',
            field=models.CharField(max_length=50),
        ),
    ]
