# Generated by Django 2.2 on 2020-05-18 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0015_auto_20200518_0024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtistInfo',
        ),
    ]
