# Generated by Django 2.2 on 2020-05-18 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0016_delete_artistinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=25)),
                ('profile', models.CharField(max_length=50)),
                ('members', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=100)),
                ('record_label', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='logreg.User')),
            ],
        ),
    ]
