# Generated by Django 3.0.5 on 2020-05-19 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0020_auto_20200519_0126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtistImage',
        ),
    ]
