# Generated by Django 3.0.5 on 2020-05-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0021_delete_artistimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('artist_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
