# Generated by Django 3.0.5 on 2020-05-19 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0022_artistimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistimage',
            name='title',
        ),
    ]
