# Generated by Django 3.0.5 on 2020-05-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0023_remove_artistimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistinfo',
            name='artist_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
